name: STAGING

on:
  push:
    branches: [development]

jobs:
  build_client:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./client

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --force
      - run: yarn run build
      - run: rm -r /var/www/html/staging-leaguedex/*
      - run: mv ./build/* /var/www/html/staging-leaguedex
      - run: rm -r ./
  build_server:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./server

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cp ../../server.env ./.env
      - run: cp ../../prisma.env ./prisma/.env
      - run: mv ./ ../staging_leaguedex
      - run: cd ../staging_leaguedex
      - run: yarn install --force
      - run: yarn build
      - run: prisma migrate up --experimental
      - run: prisma generate
      - run: yarn restart:staging
